name: Pull Request Comment Action
on:
  issue_comment:
    types: [created]

jobs:
  bump:
    name: Pull Request Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.name github-actions && git config user.email github-actions@github.com
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: sqren/pr-push-action@v1
        with:
          comment: 'please bump'
          command: yarn bump
      - uses: sqren/pr-push-action@v1
        with:
          comment: 'please yoyo'
          command: yarn yolo
