name: Pull Request Comment Action
on:
  issue_comment:
    types: [created]

jobs:
  bump:
    name: Pull Request Comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git config user.name github-actions && git config user.email github-actions@github.com
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Bump
        uses: sqren/pr-push-action@v1
        with:
          comment: 'please bump'
          command: yarn bump
      - name: Yolo
        uses: sqren/pr-push-action@v1
        with:
          comment: 'please yoyo'
          command: yarn yolo
