name: Pull Request Comment Action
on:
  issue_comment:
    types: [created]

jobs:
  bump:
    name: Pull Request Comment
    runs-on: ubuntu-latest
    steps:
      - uses: sqren/pr-push-action@v1
        with:
          comment: 'please bump'
          command: yarn bump
      - uses: sqren/pr-push-action@v1
        with:
          comment: 'please yoyo'
          command: yarn yolo
